### ISSUE TITLE
Failed to parse NetParameter file

### ISSUE THREAD

**Issue by chendongai** [LifeBeyondExpectations/YOLO_on_the_ROS#1]
When I run this demo,I meet the following error.
Can you help me ?
check the version opencv.
3.3.1
/usr/local/lib/python2.7/dist-packages/cv2.so
init darknet
OpenCV Error: Parsing error (Failed to parse NetParameter file: /home/jaesungchoe/catkin_ws/src/yolo/src/darknet/cfg/yolo.cfg) in ReadNetParamsFromCfgFileOrDie, file /tmp/opencv-3.3.1/modules/dnn/src/darknet/darknet_io.cpp, line 612
Traceback (most recent call last):
  File "yolo.py", line 206, in <module>
    myDarknetInst.__int__() # do I have to write this initializer??
  File "yolo.py", line 39, in __int__
    self.net = cv2.dnn.readNetFromDarknet((path_darknet + param_cfg), (path_darknet + param_model))
cv2.error: /tmp/opencv-3.3.1/modules/dnn/src/darknet/darknet_io.cpp:612: error: (-212) Failed to parse NetParameter file: /home/jaesungchoe/catkin_ws/src/yolo/src/darknet/cfg/yolo.cfg in function ReadNetParamsFromCfgFileOrDie

**Comment by wbzhang233** [comment]
Hey, I'm facing this problem too. Do you solve this problem yet? My opencv version is 3.2.0, it seem ok, but I have to install darknet.
Hoping for your help! Sincerely.
